INSERT INTO users (firstName, lastName, email, password, role) VALUES ('Alice', 'Martin', 'alice.martin@email.com', 'Admin1234!', 'ADMIN')
INSERT INTO users (firstName, lastName, email, password, role) VALUES ('Bruno', 'Lefevre', 'bruno.lefevre@email.com', 'Bruno5678!', 'RESTAURANT_OWNER')
INSERT INTO users (firstName, lastName, email, password, role) VALUES ('Claire', 'Dupont', 'claire.dupont@email.com', 'Claire9012!', 'RESTAURANT_OWNER')
INSERT INTO users (firstName, lastName, email, password, role) VALUES ('David', 'Moreau', 'david.moreau@email.com', 'David3456!', 'CUSTOMER')
INSERT INTO users (firstName, lastName, email, password, role) VALUES ('Emilie', 'Bernard', 'emilie.bernard@email.com', 'Emilie7890!', 'CUSTOMER')
INSERT INTO users (firstName, lastName, email, password, role) VALUES ('Francois', 'Petit', 'francois.petit@email.com', 'Francois2345!', 'CUSTOMER')
INSERT INTO dishes (name, description, price, is_available, owner_id) VALUES ('Steak frites', 'Entrecote grillee 200g avec frites maison et sauce bearnaise', 18.50, 1, 2)
INSERT INTO dishes (name, description, price, is_available, owner_id) VALUES ('Croque-monsieur', 'Pain de mie, jambon blanc, emmental fondu, bechamel', 9.90, 1, 2)
INSERT INTO dishes (name, description, price, is_available, owner_id) VALUES ('Soupe a l''oignon', 'Soupe gratinee a l''oignon avec croutons et gruyere', 8.50, 1, 2)
INSERT INTO dishes (name, description, price, is_available, owner_id) VALUES ('Tarte Tatin', 'Tarte aux pommes caramelisees, servie tiede avec creme fraiche', 7.00, 0, 2)
INSERT INTO dishes (name, description, price, is_available, owner_id) VALUES ('Pad Thai', 'Nouilles sautees au poulet, cacahuetes, oeuf, sauce tamarin', 13.90, 1, 3)
INSERT INTO dishes (name, description, price, is_available, owner_id) VALUES ('Rouleaux de printemps', 'Rouleaux frais aux crevettes, vermicelles et menthe (x3)', 7.50, 1, 3)
INSERT INTO dishes (name, description, price, is_available, owner_id) VALUES ('Riz cantonais', 'Riz saute aux legumes, oeufs et jambon', 10.50, 1, 3)
INSERT INTO dishes (name, description, price, is_available, owner_id) VALUES ('Soupe pho', 'Bouillon de boeuf, nouilles de riz, herbes fraiches', 12.00, 1, 3)